### ISSUE TITLE
Function search missing

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/pursuit#222] opened 2016-06-25 16:30 UTC
If I search for something like `>>=` or `>=>` or `>>>`, nothing comes up, but I can do this in Hoogle.

Maybe this was never implemented, but I thought I remember this working earlier.

**Comment by jplatte** [comment] 2016-06-25 16:54
This doesn't apply to operators only. The pursuit search search hardly works at all currently (see #221).

**Comment by hdgarrood** [comment] 2016-06-26 02:07
It did used to work, yes. This is a duplicate of #221.

**Closed by hdgarrood** 2016-06-26 02:07 UTC
