### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by user471** [purescript/pursuit#174] opened 2015-12-12 06:11 UTC
Are there any plans for command line version?

**Comment by hdgarrood** [comment] 2015-12-12 06:15
Possibly. What would you want it to do, and why? Also I think `psc-ide` already has some level of pursuit integration: https://github.com/kRITZCREEK/psc-ide

**Comment by user471** [comment] 2015-12-12 06:45
>What would you want it to do, and why?

Same as hoogle version. For example, any editor integration.

> Also I think psc-ide already has some level of pursuit integration

I think version without web request would be better option.

**Comment by hdgarrood** [comment] 2015-12-12 07:03
I'm not familiar with the hoogle version, could you expand a bit more? There is already a project for editor integration: `psc-ide`. In fact, I think `psc-ide` might be exactly what you're after, especially if you want it to operate only on the code in your current project.

**Comment by user471** [comment] 2015-12-12 07:19
>I'm not familiar with the hoogle version, could you expand a bit more? 

http://hackage.haskell.org/package/hoogle
In Emacs you could do this

![1](https://cloud.githubusercontent.com/assets/5988253/11760780/84a7a416-a0b9-11e5-92c1-0d356683c4d4.png)
![2](https://cloud.githubusercontent.com/assets/5988253/11760781/8cc71f78-a0b9-11e5-9af2-002b10d40fa9.png)

>There is already a project for editor integration: psc-ide.

But it use web requests to Purescript. Command line version would just have more sense in this scenario.

**Comment by hdgarrood** [comment] 2015-12-12 08:35
/cc @kritzcreek, please correct me if I'm wrong:

My impression is that `psc-ide` aims to be *the* command line tool for PureScript editor integration. I am fairly sure that if it does not currently have a command for searching through all the identifiers in locally installed code, then such a command would be in scope for `psc-ide`, and should be implemented there, not here. I definitely don't want to introduce any fragmentation; having just one tool for editor integration feels like the right approach.

Now, if such a command were to be implemented in `psc-ide` via Hoogle, i.e. using a Hoogle database populated with all the locally installed code, then `psc-ide` would be able to benefit from the Hoogle stuff I've done inside pursuit already. In that case, I think the best approach would be to extract a library from pursuit for the hoogle stuff, and have `psc-ide` depend on that. I would be very happy to include that, if someone on the `psc-ide` side could give me an idea of what the API would ideally look like.

**Comment by kRITZCREEK** [comment] 2015-12-12 09:36
`psc-ide` already does this. At least the usecases that your screenshots describe. (Module and Type lookup) It does not show you the documentation for a given function yet, but that is on the horizon.

If we wanted to locally install a hoogle database to be able to search by types I suggest we made Pursuit installable and queried a local pursuit server from `psc-ide`.

The lookup queries and protocol can be found [here](https://github.com/kRITZCREEK/psc-ide/blob/master/PROTOCOL.md). From an emacs point of view it shouldn't be too hard to push some of these suggestions into a helm buffer to get the same "hoogly" feeling.

**Comment by hdgarrood** [comment] 2015-12-12 09:39
Ok, sounds good, thanks. Then I will close this as a duplicate of #70.

**Closed by hdgarrood** 2015-12-12 09:39 UTC
