### ISSUE TITLE
Function signature for the top-most result of 'sequence' isn't rendered

### ISSUE THREAD

**Issue by wereHamster** [purescript/pursuit#279] opened 2017-01-30 08:14 UTC
When I was searching if PureScript has the standard `sequence` function I couldn't find it. It turns out I was confused because the top-most hit in the results doesn't render the function signature, and I was scanning the results for the correct function signature (`t (m a) -> m (t a)`). See the screenshot below.

Is it because it's a class function rather than a standalone function? Observe that no signature is shown for `Sequence` from purescript-webdriver, which is a newtype.

![screen shot 2017-01-30 at 09 09 12](https://cloud.githubusercontent.com/assets/34538/22416024/ebe13d14-e6cb-11e6-9f83-c1506ca19751.png)

**Comment by hdgarrood** [comment] 2017-01-30 12:59
Thanks for the report - yes, I think this is a duplicate of #264.

**Closed by hdgarrood** 2017-01-30 12:59 UTC
