### ISSUE TITLE
Source links are broken

### ISSUE THREAD

**Issue by jkachmar** [purescript/pursuit#332] opened 2017-08-29 13:57 UTC
Uploaded documentation seems to generate incorrect links to the source code.

e.g. I uploaded docs for `purescript-parallel` v3.2.0 with `pulp publish --no-push` and it generated this link for `parTraverse`:

https://github.com/purescript/purescript-parallel/blob/v3.2.0/src/purescript-parallel/src/Control/Parallel.purs#L20-L26

when it should have generated this link:

https://github.com/purescript/purescript-parallel/blob/v3.2.0/src/Control/Parallel.purs#L20-L26

The rest of the package has links that are similarly broken.

Links from the `purescript-parallel` v3.0.0 docs on Pursuit work as-expected.

**Comment by hdgarrood** [comment] 2017-08-30 22:04
Thanks for the report, I'll look into it.

**Comment by hdgarrood** [comment] 2017-09-04 18:55
I just tried to reproduce this and was unable to. Can you give me the exact set of steps you used to upload the package? I also uploaded the docs again to Pursuit to make the source links work, just FYI.

**Comment by hdgarrood** [comment] 2017-11-20 21:41
Closing because I haven't been able to reproduce. Please reopen if you have repro steps.

**Closed by hdgarrood** 2017-11-20 21:41 UTC
