### ISSUE TITLE
Pretty print type signature

### ISSUE THREAD

**Issue by coot** [purescript/pursuit#333] opened 2017-09-06 19:37 UTC
It would be nice to have pretty printed type signatures, since complex type signatures are not [readable](https://pursuit.purescript.org/packages/purescript-cofree-react-router/6.3.0/docs/React.Router.Utils#v:composeFL).

**Comment by hdgarrood** [comment] 2017-09-07 12:42
Agree, definitely. This is a duplicate of https://github.com/purescript/purescript/issues/1538 so I'll close though.

**Closed by hdgarrood** 2017-09-07 12:42 UTC
