### ISSUE TITLE
Request: Clickable modules in search

### ISSUE THREAD

**Issue by fosskers** [purescript/pursuit#368] opened 2018-01-24 23:07 UTC
When one searches for a function or type, it may be that they really want to get to the module/package it belongs to. However, those aren't currently clickable:

![2018-01-24-150109_1918x1078_scrot](https://user-images.githubusercontent.com/229679/35361976-5591b4a2-0118-11e8-945a-9d2d3e940bc1.png)

In this case, it would be convenient if `purescript-prelude` and `Control.Applicative` at the bottom were clickable. Can they be made to be?

**Comment by hdgarrood** [comment] 2018-01-25 00:37
They could, yes. I’ll close this since it is a duplicate of #268.

**Closed by hdgarrood** 2018-01-25 00:37 UTC

**Comment by fosskers** [comment] 2018-01-25 00:59
Ah woops, forgive the noise.

**Comment by hdgarrood** [comment] 2018-01-25 01:32
No worries :)
