### ISSUE TITLE
Adding more code examples

### ISSUE THREAD

**Issue by Cmdv** [purescript/pursuit#284] opened 2017-02-14 21:44 UTC
Been thinking about having the ability to extend pursuit to be able to display more in depth code examples.
As a beginner it would be so good to see functions in actions, if you compare `map` on:

[Pursuit](https://pursuit.purescript.org/packages/purescript-prelude/2.4.0/docs/Data.Functor#v:map) vs [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

@rightfold mentioned [Go Lang](https://golang.org/pkg/encoding/json/#example_Decoder) as another good example, they seem to have separate `examples` files in the repo rather than having it all as comments in the source code. Which I thought was cool as these extra examples in the source code might just make the size of the files a little too much!

The idea would be not to change current functionality but rather add the ability to pull in say `example_[functioname].purs` files and display those as well.

Think that starting on `Prelude` would be a great starting point and I would happily help make these examples if people are keen on the idea. I'd really appreciate it if someone could pair or help me with implementing the functionality, it's just I think I would struggle doing it on my own. 😄

**Comment by paf31** [comment] 2017-02-14 21:49
Why not just include examples as markdown code blocks?

**Comment by garyb** [comment] 2017-02-14 21:50
A long time ago I added extensive comments to the `Maybe` instances illustrating various ways they could be used: https://github.com/purescript/purescript-maybe/blob/299f5e583fe5a2f6d505e2bae13f71928c007ee6/src/Data/Maybe.purs but unfortunately these don't show up in Pursuit. I think there was another issue that talked about showing comments on instances, but I assume it was shot down since I can't find the issue and we can't see the docs :smile:

**Comment by rightfold** [comment] 2017-02-14 21:50
@paf31 Markdown code blocks in comments aren't compiled as part of your tests and they take up a lot of space in the source code.

**Comment by rightfold** [comment] 2017-02-14 21:50
I'd be fine with putting examples in separate directory, such that you'd have `src`, `test`, and `example`.

**Comment by paf31** [comment] 2017-02-14 21:52
How would they be executed? What's stopping us from executing examples if they are included in markdown blocks?

I say I prefer to use markdown because then `psc-docs` gets to benefit as well.

**Comment by rightfold** [comment] 2017-02-14 21:52
How do you tell which comments are examples and which aren't? Surround them with some marker?

**Comment by Cmdv** [comment] 2017-02-14 21:53
@paf31 ah ok cool, it was more an idea I wasn't 100% on implementation or what would be easiest for a library dev. Just keen to get more thorough examples :)

**Comment by LiamGoodacre** [comment] 2017-02-14 21:53
Possibly for inspiration: https://github.com/tpolecat/tut

**Comment by Cmdv** [comment] 2017-02-14 21:55
@garyb oh yeah that is great, shame it doesn't pull it all in :(

**Comment by rightfold** [comment] 2017-02-14 21:57
This may also help with examples: https://github.com/purescript/purescript/issues/2525 If you don't want them to belong to a particular function, but to a group of functions for example.

**Comment by paf31** [comment] 2017-02-14 22:08
I wrote something called purs.md a while ago, along these lines. The problem is that it requires Try PureScript, which only supports the core libraries. There is `flaredoc` as well, of course.

**Comment by Cmdv** [comment] 2017-02-14 22:13
@paf31 this [flaredoc](https://github.com/sharkdp/purescript-flaredoc)?
I'd be more than happy to add more examples if you think we can get away with not adding any functionality but seems that some bits don't get pulled in correctly so maybe I should look there first.

**Comment by hdgarrood** [comment] 2017-02-14 22:58
> A long time ago I added extensive comments to the Maybe instances illustrating various ways they could be used

@garyb I still want to do that! https://github.com/purescript/pursuit/issues/159#issuecomment-216234062

**Comment by garyb** [comment] 2017-02-14 23:49
Ah sorry, I missed that somehow :)

**Comment by hdgarrood** [comment] 2017-12-07 16:12
I think I'm going to close this, as there's been no movement for a while and we haven't really been able to agree on a way forward. At the moment you can include examples inline or link to Try PureScript. Checking that code examples still compile is definitely worth doing but is a separate issue, I think.

**Closed by hdgarrood** 2017-12-07 16:12 UTC
